Repository w3c/webdriver, pull requests merged in 2018-11, with the labels that each got.

#1325 Don't perform interactability checks for send keys to input type=file
  index.html
Labels: requires test

#1357 actions: reorganise chapter
  index.html
Labels: enhancement

#1356 Move index of definitions to end of document
  index.html
Labels: enhancement

#1351 collection: use instance checks
  index.html
Labels: bug

#1352 collection: check for "Arguments" string
  index.html
Labels: bug

#1324 Add a endpoint for creating a new window.
  index.html
Labels: requires test
